### ISSUE TITLE
Set default value for continuouslyUpdatesValue to true

### ISSUE THREAD

**Issue by vikmeup** [seedco/Formalist#30]
Regarding this line of code https://github.com/seedco/Formalist/blob/master/Formalist/TextEditorConfiguration.swift#L47

In most cases value  needs to be updated right away, otherwise if form gets in the state where  `form.validate()` is called, but user did not resign from textField or textView.

**Comment by klaaspieter** [comment]
Looks like that's the case already https://github.com/seedco/Formalist/blob/5916879172bd2be3c6db1090d7c84ee34c905c5c/Formalist/TextEditorConfiguration.swift#L70
